"""
MMR diversity baseline for saved recommendation lists.

This module reranks an existing ``recommendations.pkl`` file generated by a
RecBole baseline. It keeps the same users and candidate lists, then applies
Maximal Marginal Relevance (MMR) using saved user/item embeddings.
"""

import argparse
import json
import pickle
import struct
from configparser import ConfigParser
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Optional, Sequence


PROJECT_ROOT = Path(__file__).resolve().parents[1]


class _FallbackDType:
    def __init__(self, *args, **kwargs):
        self.args = args
        self.code = args[0] if args else None

    def __setstate__(self, state):
        self.state = state


class _FallbackNdarray:
    def __setstate__(self, state):
        self.state = state

    def tolist(self):
        if isinstance(self.state, tuple) and len(self.state) >= 5:
            _, shape, dtype, _, data = self.state[:5]
            size = 1
            for dimension in shape:
                size *= dimension
            if isinstance(data, bytes):
                code = getattr(dtype, "code", "")
                if code == "f4":
                    return list(struct.unpack(f"<{size}f", data))
                if code == "f8":
                    return list(struct.unpack(f"<{size}d", data))
            return list(data)
        return []


def _fallback_scalar(dtype, data):
    code = getattr(dtype, "code", "")
    if isinstance(data, bytes) and str(code).startswith("U"):
        return data.decode("utf-32le").rstrip("\x00")
    try:
        return float(data.decode().rstrip("\x00"))
    except Exception:
        return 0.0


def _fallback_reconstruct(*args):
    return _FallbackNdarray()


class _FallbackUnpickler(pickle.Unpickler):
    def find_class(self, module, name):
        if module == "numpy" and name == "dtype":
            return _FallbackDType
        if module == "numpy" and name == "ndarray":
            return _FallbackNdarray
        if module == "numpy.core.multiarray" and name == "_reconstruct":
            return _fallback_reconstruct
        if module == "numpy.core.multiarray" and name == "scalar":
            return _fallback_scalar
        return super().find_class(module, name)


def load_pickle(path: Path):
    with open(path, "rb") as f:
        try:
            return pickle.load(f)
        except ModuleNotFoundError as exc:
            if exc.name != "numpy":
                raise
            f.seek(0)
            return _FallbackUnpickler(f).load()


def save_pickle(obj, path: Path) -> None:
    with open(path, "wb") as f:
        pickle.dump(obj, f)


def vector_to_list(vector) -> List[float]:
    if hasattr(vector, "tolist"):
        vector = vector.tolist()
    return [float(value) for value in vector]


def cosine_similarity(first: Sequence[float], second: Sequence[float]) -> float:
    dot = 0.0
    first_norm = 0.0
    second_norm = 0.0
    for first_value, second_value in zip(first, second):
        dot += first_value * second_value
        first_norm += first_value * first_value
        second_norm += second_value * second_value
    if first_norm == 0.0 or second_norm == 0.0:
        return 0.0
    return dot / ((first_norm ** 0.5) * (second_norm ** 0.5))


def rank_relevance(candidate_items: Sequence[str]) -> Dict[str, float]:
    denominator = max(len(candidate_items), 1)
    return {
        item_id: (denominator - rank) / denominator
        for rank, item_id in enumerate(candidate_items)
    }


def embedding_relevance(
    user_id: str,
    candidate_items: Sequence[str],
    user_embeddings: Mapping[str, object],
    item_embeddings: Mapping[str, object],
    user_token_map: Mapping[str, str],
    item_token_map: Mapping[str, str],
) -> Dict[str, float]:
    relevance = rank_relevance(candidate_items)
    user_token = user_token_map.get(user_id, user_id)
    if user_token not in user_embeddings:
        return relevance

    user_vector = vector_to_list(user_embeddings[user_token])
    for item_id in candidate_items:
        item_token = item_token_map.get(item_id, item_id)
        if item_token not in item_embeddings:
            continue
        relevance[item_id] = cosine_similarity(
            user_vector, vector_to_list(item_embeddings[item_token])
        )
    return relevance


def item_similarity(
    first_item_id: str,
    second_item_id: str,
    item_embeddings: Mapping[str, object],
    item_token_map: Mapping[str, str],
) -> float:
    first_token = item_token_map.get(first_item_id, first_item_id)
    second_token = item_token_map.get(second_item_id, second_item_id)
    if first_token not in item_embeddings or second_token not in item_embeddings:
        return 0.0
    return cosine_similarity(
        vector_to_list(item_embeddings[first_token]),
        vector_to_list(item_embeddings[second_token]),
    )


def rerank_with_mmr(
    user_id: str,
    candidate_items: Sequence[str],
    user_embeddings: Mapping[str, object],
    item_embeddings: Mapping[str, object],
    user_token_map: Mapping[str, str],
    item_token_map: Mapping[str, str],
    lambda_weight: float,
    top_k: Optional[int] = None,
) -> List[str]:
    if lambda_weight < 0.0 or lambda_weight > 1.0:
        raise ValueError("lambda_weight must be between 0 and 1")

    limit = min(top_k or len(candidate_items), len(candidate_items))
    remaining = list(dict.fromkeys(candidate_items))
    relevance = embedding_relevance(
        user_id,
        remaining,
        user_embeddings,
        item_embeddings,
        user_token_map,
        item_token_map,
    )

    selected = []
    while remaining and len(selected) < limit:
        if not selected:
            best_item = max(remaining, key=lambda item_id: relevance.get(item_id, 0.0))
        else:
            best_item = max(
                remaining,
                key=lambda item_id: (
                    lambda_weight * relevance.get(item_id, 0.0)
                    - (1.0 - lambda_weight)
                    * max(
                        item_similarity(item_id, selected_item, item_embeddings, item_token_map)
                        for selected_item in selected
                    )
                ),
            )
        selected.append(best_item)
        remaining.remove(best_item)
    return selected


def rerank_recommendations(
    recommendations: Iterable[Mapping[str, object]],
    user_embeddings: Mapping[str, object],
    item_embeddings: Mapping[str, object],
    user_token_map: Mapping[str, str],
    item_token_map: Mapping[str, str],
    lambda_weight: float,
    top_k: Optional[int] = None,
) -> List[Dict[str, object]]:
    reranked = []
    for recommendation in recommendations:
        user_id = str(recommendation["user_id"])
        candidate_items = [str(item_id) for item_id in recommendation["recommended_items"]]
        reranked.append(
            {
                "user_id": recommendation["user_id"],
                "recommended_items": rerank_with_mmr(
                    user_id,
                    candidate_items,
                    user_embeddings,
                    item_embeddings,
                    user_token_map,
                    item_token_map,
                    lambda_weight,
                    top_k,
                ),
            }
        )
    return reranked


def load_config(config_path: Path) -> ConfigParser:
    config = ConfigParser()
    config.read(config_path)
    return config


def resolve_save_dir(args) -> Path:
    if args.save_dir:
        return Path(args.save_dir)

    config = load_config(PROJECT_ROOT / "common" / "parameter.ini")
    dataset = args.dataset or config.get("simulation", "dataset")
    recommender = args.recommender or config.get("simulation", "recommender")
    return PROJECT_ROOT / "saved" / dataset / recommender


def run_mmr_baseline(
    save_dir: Path,
    lambda_weight: float,
    top_k: Optional[int],
    output_name: str,
) -> Path:
    recommendations = load_pickle(save_dir / "recommendations.pkl")
    user_embeddings = load_pickle(save_dir / "user_embedding.pkl")
    item_embeddings = load_pickle(save_dir / "item_embedding.pkl")

    with open(save_dir / "user_token_map.json") as f:
        user_token_map = json.load(f)
    with open(save_dir / "item_token_map.json") as f:
        item_token_map = json.load(f)

    reranked = rerank_recommendations(
        recommendations,
        user_embeddings,
        item_embeddings,
        user_token_map,
        item_token_map,
        lambda_weight=lambda_weight,
        top_k=top_k,
    )

    output_path = save_dir / output_name
    save_pickle(reranked, output_path)
    return output_path


def parse_args():
    config = load_config(PROJECT_ROOT / "common" / "parameter.ini")
    default_lambda = config.getfloat("mmr", "lambda", fallback=0.7)
    default_top_k = config.getint(
        "mmr",
        "top_k",
        fallback=config.getint("recommender", "top_k", fallback=None),
    )

    parser = argparse.ArgumentParser(
        description="Run MMR over generated recommender artifacts."
    )
    parser.add_argument("--dataset", help="Dataset folder under saved/.")
    parser.add_argument("--recommender", help="Recommender folder under saved/<dataset>/.")
    parser.add_argument("--save-dir", help="Explicit directory containing generated artifacts.")
    parser.add_argument("--lambda-weight", type=float, default=default_lambda)
    parser.add_argument("--top-k", type=int, default=default_top_k)
    parser.add_argument("--output-name", default="mmr_recommendations.pkl")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output_path = run_mmr_baseline(
        resolve_save_dir(args),
        lambda_weight=args.lambda_weight,
        top_k=args.top_k,
        output_name=args.output_name,
    )
    print(f"Saved MMR recommendations to {output_path}")


if __name__ == "__main__":
    main()
