name: yin-yang-recommendation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pip
  - poetry
  - pip:
      - torch==2.5.1
      - torchvision==0.20.1
      - torchaudio==2.5.1
      - transformers
      - huggingface_hub
      - recbole==1.2.0
      - networkx
      - scikit-learn
      - pandas
      - plotly
      - tensorboard
      - tqdm
      - pyyaml
      - colorlog