name: yin-yang-recommendation
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=25.0
  - python=3.9.21
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.2.0
      - aiosignal==1.3.2
      - attrs==25.3.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - cmake==3.31.6
      - colorama==0.4.4
      - colorlog==4.7.2
      - filelock==3.18.0
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - future==1.0.0
      - grpcio==1.71.0
      - huggingface-hub==0.29.3
      - hyperopt==0.2.5
      - idna==3.10
      - importlib-metadata==8.6.1
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - lit==18.1.8
      - markdown==3.7
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - narwhals==1.31.0
      - networkx==3.2.1
      - nltk==3.9.1
      - numpy==1.23.5
      - packaging==24.2
      - pandas==2.2.3
      - plotly==6.0.1
      - protobuf==6.30.1
      - psutil==7.0.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - ray==2.6.3
      - recbole==1.2.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rpds-py==0.23.1
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.6.0
      - six==1.17.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - textblob==0.17.1
      - texttable==1.7.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - tokenizers==0.15.2
      - torch==2.0.0
      - tqdm==4.67.1
      - transformers==4.36.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - werkzeug==3.1.3
      - zipp==3.21.0