SELECTED_METHODS = ['NGCF', 'LGCN', 'DGCF', 'Random']
SELECTIVE_DATASETS = ["movie", "book", "news"]
ITEM_FILE = "items.tsv"
ITEM_PICKLE_FILE = "items.pkl"
USER_PICKLE_FILE = "users.pkl"
USER_FILE = "new_behaviors.tsv"
MAX_WORDS = 300
DIM = 100
NUM_THREADS = 32